export const bancos = [
    { "avatar": "/agibanco-icon.png", "banco": "Agibanco" },
    { "avatar": "/bb-icon.png", "banco": "Banco do Brasil" },
    { "avatar": "/bradesco-icon.png", "banco": "Bradesco" },
    { "avatar": "/brb-icon.png", "banco": "BRB" },
    { "avatar": "/bs2-icon.png", "banco": "BS2" },
    { "avatar": "/btg-icon.png", "banco": "BTG Pactual" },
    { "avatar": "/c6-bank-icon.png", "banco": "C6 Bank" },
    { "avatar": "/caixa-icon.png", "banco": "Caixa Econômica" },
    { "avatar": "/digio-icon.png", "banco": "Digio" },
    { "avatar": "/inter-icon.png", "banco": "Banco Inter" },
    { "avatar": "/itau-icon.png", "banco": "Itaú Unibanco" },
    { "avatar": "/iti-icon.png", "banco": "Iti" },
    { "avatar": "/mercado-pago-icon.png", "banco": "Mercado Pago" },
    { "avatar": "/neon-icon.png", "banco": "Neon" },
    { "avatar": "/next-icon.png", "banco": "Next" },
    { "avatar": "/nubank-icon.png", "banco": "Nubank" },
    { "avatar": "/original-icon.png", "banco": "Banco Original" },
    { "avatar": "/pag-bank-icon.png", "banco": "Pag Bank" },
    { "avatar": "/pag-seguro-icon.png", "banco": "Pag Seguro" },
    { "avatar": "/pan-icon.png", "banco": "Banco PAN" },
    { "avatar": "/picpay-icon.png", "banco": "Picpay" },
    { "avatar": "/safra-icon.png", "banco": "Safra" },
    { "avatar": "/santander-icon.png", "banco": "Santander" },
    { "avatar": "/sicredi-icon.png", "banco": "Sicredi" }
]
